"""creation table apprenant

Revision ID: 689a4e81ebfc
Revises: 
Create Date: 2025-06-10 22:13:50.189877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689a4e81ebfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.Column('niveau_acces', sa.Enum(), nullable=True),
    sa.Column('date_promotion', sa.Date(), nullable=True),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('mdp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_admin')
    )
    op.create_table('apprenant',
    sa.Column('id_apprenant', sa.Integer(), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('date_inscription', sa.Date(), nullable=True),
    sa.Column('niveau_etude', sa.Enum(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('mdp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_apprenant')
    )
    op.create_table('formateur',
    sa.Column('id_formateur', sa.Integer(), nullable=False),
    sa.Column('specialites', sa.String(), nullable=True),
    sa.Column('date_embauche', sa.Date(), nullable=True),
    sa.Column('taux_horaire', sa.Float(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('mdp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_formateur')
    )
    op.create_table('support',
    sa.Column('id_support', sa.Integer(), nullable=False),
    sa.Column('poste', sa.Enum(), nullable=True),
    sa.Column('date_prise_fonction', sa.Date(), nullable=True),
    sa.Column('responsabilites', sa.JSON(), nullable=True),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('mdp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_support')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support')
    op.drop_table('formateur')
    op.drop_table('apprenant')
    op.drop_table('admin')
    # ### end Alembic commands ###
