"""deuxieme migration

Revision ID: 774ab6ca6306
Revises: a7bfe0c883e0
Create Date: 2025-06-11 13:11:46.370637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774ab6ca6306'
down_revision = 'a7bfe0c883e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formateur',
    sa.Column('id_formateur', sa.Integer(), nullable=False),
    sa.Column('specialites', sa.String(), nullable=True),
    sa.Column('date_embauche', sa.Date(), nullable=True),
    sa.Column('taux_horaire', sa.Float(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('mdp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_formateur')
    )
    op.create_table('support',
    sa.Column('id_support', sa.Integer(), nullable=False),
    sa.Column('poste', sa.Enum(), nullable=True),
    sa.Column('date_prise_fonction', sa.Date(), nullable=True),
    sa.Column('responsabilites', sa.JSON(), nullable=True),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('mdp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_support')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support')
    op.drop_table('formateur')
    # ### end Alembic commands ###
