"""premiere migration

Revision ID: a7bfe0c883e0
Revises: 
Create Date: 2025-06-11 13:09:43.315421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7bfe0c883e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.Column('niveau_acces', sa.Enum(), nullable=True),
    sa.Column('date_promotion', sa.Date(), nullable=True),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('mdp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_admin')
    )
    op.create_table('apprenant',
    sa.Column('id_apprenant', sa.Integer(), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('date_inscription', sa.Date(), nullable=True),
    sa.Column('niveau_etude', sa.Enum(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('mdp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_apprenant')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apprenant')
    op.drop_table('admin')
    # ### end Alembic commands ###
