"""ajout salles et certifications

Revision ID: d7a0b4e526b3
Revises: 774ab6ca6306
Create Date: 2025-06-11 16:01:03.623542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a0b4e526b3'
down_revision = '774ab6ca6306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certification',
    sa.Column('id_certification', sa.SmallInteger(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_certification')
    )
    op.create_table('salle',
    sa.Column('id_salle', sa.SmallInteger(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('capacite', sa.SmallInteger(), nullable=True),
    sa.Column('localisation', sa.String(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_salle')
    )
    op.create_table('apprenant_certification',
    sa.Column('id_apprenant', sa.Integer(), nullable=False),
    sa.Column('id_certification', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_apprenant'], ['apprenant.id_apprenant'], ),
    sa.ForeignKeyConstraint(['id_certification'], ['certification.id_certification'], ),
    sa.PrimaryKeyConstraint('id_apprenant', 'id_certification')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apprenant_certification')
    op.drop_table('salle')
    op.drop_table('certification')
    # ### end Alembic commands ###
